/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MAIN;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author AntonDaryl
 */
public class DeleteUser extends javax.swing.JFrame {
    
 private static String name, pass;
    private static final String filepath = "src\\MAIN\\DATA.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject use = new JSONObject();
    private static JSONArray userlist = new JSONArray();
    private static JSONObject record = new JSONObject();
    /**
     * Creates new form DeleteUser
     */
    public DeleteUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtUserDlt = new javax.swing.JTextField();
        jTxtPassDlt = new javax.swing.JPasswordField();
        jUserDelete = new javax.swing.JLabel();
        jPassDelete = new javax.swing.JLabel();
        CancelBtnDlt = new javax.swing.JButton();
        ClearBtnDlt = new javax.swing.JButton();
        DltBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jUserDelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jUserDelete.setForeground(new java.awt.Color(255, 255, 255));
        jUserDelete.setText("Enter Username:");

        jPassDelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPassDelete.setForeground(new java.awt.Color(255, 255, 255));
        jPassDelete.setText("Enter Password:");

        CancelBtnDlt.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CancelBtnDlt.setText("Cancel");
        CancelBtnDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnDltActionPerformed(evt);
            }
        });

        ClearBtnDlt.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ClearBtnDlt.setText("Clear");
        ClearBtnDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnDltActionPerformed(evt);
            }
        });

        DltBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        DltBtn.setText("Delete");
        DltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserDelete)
                    .addComponent(jPassDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtUserDlt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTxtPassDlt))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CancelBtnDlt)
                .addGap(45, 45, 45)
                .addComponent(ClearBtnDlt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(DltBtn)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUserDlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserDelete))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPassDlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtnDlt)
                    .addComponent(ClearBtnDlt)
                    .addComponent(DltBtn))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnDltActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
                a.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_CancelBtnDltActionPerformed

    private void ClearBtnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnDltActionPerformed
        // TODO add your handling code here:
            jTxtUserDlt.setText("");
            jTxtPassDlt.setText("");
    }//GEN-LAST:event_ClearBtnDltActionPerformed

    private void DltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltBtnActionPerformed
        // TODO add your handling code here:
       name = jTxtUserDlt.getText().trim(); // Trim to remove unnecessary spaces
    pass = jTxtPassDlt.getText().trim();

    if (name.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter username and password.", "Message", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete this student?", "Delete Student", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            filecheck(); // Load the user list

            boolean found = false;

            for (int a = 0; a < userlist.size(); a++) {
                JSONObject userObject = (JSONObject) userlist.get(a);

                String foundUsername = ((String) userObject.get("username")).trim();
                String foundPassword = ((String) userObject.get("password")).trim();

                // Case-insensitive comparison to avoid mismatches
                if (name.equalsIgnoreCase(foundUsername) && pass.equals(foundPassword)) {
                    userlist.remove(a);
                    found = true;
                    break;
                }
            }

            if (found) {
                save(); // Save updated data
                JOptionPane.showMessageDialog(null, "User successfully deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                Admin A = new Admin();
                setVisible(false);
                A.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Student not found. Please check the username and password.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    }//GEN-LAST:event_DltBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser().setVisible(true);
            }
        });
    }
 public static void filecheck() throws FileNotFoundException, IOException, ParseException {
File file = new File("src/MAIN/DATA.json");

    if (!file.exists() || file.length() == 0) {
        userlist = new JSONArray();
        record = new JSONObject();
        record.put("data", userlist);
        return;
    }

    FileReader reader = new FileReader(file);
    JSONParser jsonParser = new JSONParser();
    Object obj = jsonParser.parse(reader);
    reader.close();

    if (obj instanceof JSONObject) {
        record = (JSONObject) obj;
        userlist = (JSONArray) record.get("data");

        if (userlist == null) {
            userlist = new JSONArray();
        }
    } else {
        userlist = new JSONArray();
    }
}

    public static void save() throws IOException {

        try {
    
        record.put("data", userlist);

        FileWriter file = new FileWriter(filepath);
        file.write(record.toJSONString());
        file.close();

        JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "An error Occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtnDlt;
    private javax.swing.JButton ClearBtnDlt;
    private javax.swing.JButton DltBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPassDelete;
    private javax.swing.JPasswordField jTxtPassDlt;
    private javax.swing.JTextField jTxtUserDlt;
    private javax.swing.JLabel jUserDelete;
    // End of variables declaration//GEN-END:variables
}
