/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MAIN;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author AntonDaryl
 */
public class UpdateUser extends javax.swing.JFrame {
    
private static String name, pass, newname, newpass;
    private static final String filepath = "src\\MAIN\\DATA.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONArray userlist = new JSONArray();
    private static JSONObject record = new JSONObject();

    /**
     * Creates new form UpdateUser
     */
    public UpdateUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtUserUpdt1 = new javax.swing.JTextField();
        jTxtUserUpdt2 = new javax.swing.JTextField();
        jTxtPassUpdt1 = new javax.swing.JPasswordField();
        jTxtPassUpdt2 = new javax.swing.JPasswordField();
        jUpdtCnl = new javax.swing.JButton();
        jUpdtClr = new javax.swing.JButton();
        jUpdtBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Username:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Password:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter New Username:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter New Password:");

        jUpdtCnl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jUpdtCnl.setText("Cancel");
        jUpdtCnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdtCnlActionPerformed(evt);
            }
        });

        jUpdtClr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jUpdtClr.setText("Clear");
        jUpdtClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdtClrActionPerformed(evt);
            }
        });

        jUpdtBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jUpdtBtn.setText("Update");
        jUpdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdtBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Update User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jUpdtCnl)
                        .addGap(18, 18, 18)
                        .addComponent(jUpdtClr)
                        .addGap(18, 18, 18)
                        .addComponent(jUpdtBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtUserUpdt2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPassUpdt2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPassUpdt1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtUserUpdt1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtUserUpdt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtPassUpdt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtUserUpdt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtPassUpdt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdtCnl)
                    .addComponent(jUpdtClr)
                    .addComponent(jUpdtBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdtCnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdtCnlActionPerformed
        // TODO add your handling code here:
          Admin a = new Admin();
                a.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_jUpdtCnlActionPerformed

    private void jUpdtClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdtClrActionPerformed
        // TODO add your handling code here:
        jTxtUserUpdt1.setText("");
        jTxtPassUpdt1.setText("");
        jTxtUserUpdt2.setText("");
        jTxtPassUpdt2.setText("");
    }//GEN-LAST:event_jUpdtClrActionPerformed

    private void jUpdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdtBtnActionPerformed
        // TODO add your handling code here:
        if (userlist == null) {
        JOptionPane.showMessageDialog(this, "User list is not initialized.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (userlist.size() == 0) {
        JOptionPane.showMessageDialog(this, "No users available to update.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

         name = jTxtUserUpdt1.getText();
        pass = jTxtPassUpdt1.getText();

        boolean found;

        try {

            filecheck();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "Error reading the file. Please check if the file exists and is accessible.",
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,
                    "Error parsing JSON data. The file might be corrupted or improperly formatted.",
                    "Data Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        if (name.isBlank() && pass.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please enter username and password to update.", "Enter username and password", JOptionPane.WARNING_MESSAGE);
 
        } else {

            found = false;
            for (int a = 0; a < userlist.size(); a++) {
                JSONObject userobject = (JSONObject) userlist.get(a);
                String foundusname = (String) userobject.get("username");
                String foundpass = (String) userobject.get("password");

                if (name.equals(foundusname) && pass.equals(foundpass)) {
                    newname = jTxtUserUpdt2.getText();
                    newpass = jTxtPassUpdt2.getText();

                    if (newname.isBlank() || newpass.isBlank()) {
                        JOptionPane.showMessageDialog(null, "Please enter new details to update (or enter the "
                                + "current details if you want to keep the current details).",
                                "Enter details", JOptionPane.WARNING_MESSAGE);

                        return;
                    } else if (newname.isBlank() || newpass.isBlank()) {
                        JOptionPane.showMessageDialog(null, "Please enter new details to update (or enter the "
                                + "current details if you want to keep the current details).",
                                "Enter details", JOptionPane.WARNING_MESSAGE);
                        return;
                    } else {
                        userobject.put("password", newpass);
                        userobject.put("username", newname);

                        record.put("data", userlist);
                        found = true;
                        break;

                    }

                }

            }
            if (found) {
                try {
                    save();
                    Admin A = new Admin();
                    dispose();
                    A.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(UpdateUser.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Student not found. Please enter the correct details to update.", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jUpdtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUser().setVisible(true);
            }
        });
    }
public static void filecheck() throws FileNotFoundException, IOException, ParseException {
    FileReader reader = new FileReader(filepath);
    try {
        JSONParser parser = new JSONParser();
        Object obj = parser.parse(reader);
        if (obj instanceof JSONObject) {
            record = (JSONObject) obj;
            userlist = (JSONArray) record.get("data");
        } else {
            userlist = new JSONArray(); 
        }
    } catch (ParseException e) {
        userlist = new JSONArray(); 
        throw e;
    } finally {
        reader.close();
    }
}

    public static void save() throws IOException {
        try {
            FileWriter file = new FileWriter(filepath);
            file.write(record.toJSONString());
            file.close();
            JOptionPane.showMessageDialog(null, "Updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Failed to update. " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTxtPassUpdt1;
    private javax.swing.JPasswordField jTxtPassUpdt2;
    private javax.swing.JTextField jTxtUserUpdt1;
    private javax.swing.JTextField jTxtUserUpdt2;
    private javax.swing.JButton jUpdtBtn;
    private javax.swing.JButton jUpdtClr;
    private javax.swing.JButton jUpdtCnl;
    // End of variables declaration//GEN-END:variables
}
